MACRO(HEADER_DIRECTORIES return_list dir)
    FILE(GLOB_RECURSE new_list "${dir}/*.h")
    SET(dir_list "")
    FOREACH(file_path ${new_list})
        GET_FILENAME_COMPONENT(dir_path ${file_path} PATH)
        SET(dir_list ${dir_list} ${dir_path})
    ENDFOREACH()
    LIST(REMOVE_DUPLICATES dir_list)
    SET(${return_list} ${dir_list})
ENDMACRO()

MACRO(SOURCE_FILES return_list dir)
    message("searching dir: ${dir}")
    FILE(GLOB new_list "${dir}/*.c??")
    message("SOURCE LIST ${new_list}")

    SET(dir_list "")
    FOREACH(file_path ${new_list})
        GET_FILENAME_COMPONENT(dir_path ${file_path} PATH)
        SET(dir_list ${dir_list} ${dir_path})
    ENDFOREACH()
    LIST(REMOVE_DUPLICATES dir_list)
    SET(${return_list} ${dir_list})
ENDMACRO()

function(INSTALL_DEPENDENCY dir url)
    if(NOT EXISTS "${PROJECT_SOURCE_DIR}/${dir}")
        message("Creating libraries folder")
        FILE(MAKE_DIRECTORY "${PROJECT_SOURCE_DIR}/${dir}")
    endif()
    message("Cloning: ${url}")
    execute_process(
        COMMAND git clone ${url}
        WORKING_DIRECTORY ${PROJECT_SOURCE_DIR}/${dir}
    )
endfunction()

MACRO(SUB_DIRS return_dirs dir)
    FILE(GLOB list "${PROJECT_SOURCE_DIR}/${dir}/*")
    SET(dir_list "")
    FOREACH(file_path ${list})
        SET(dir_list ${dir_list} ${file_path})
    ENDFOREACH()
    set(${return_dirs} ${dir_list})
ENDMACRO()
