/*
The MIT License (MIT)

Copyright (c) 2016 British Broadcasting Corporation.
This software is provided by Lancaster University by arrangement with the BBC.

Permission is hereby granted, free of charge, to any person obtaining a
copy of this software and associated documentation files (the "Software"),
to deal in the Software without restriction, including without limitation
the rights to use, copy, modify, merge, publish, distribute, sublicense,
and/or sell copies of the Software, and to permit persons to whom the
Software is furnished to do so, subject to the following conditions:

The above copyright notice and this permission notice shall be included in
all copies or substantial portions of the Software.

THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL
THE AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING
FROM, OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER
DEALINGS IN THE SOFTWARE.
*/

/**
  * Class definition for a DeviceEvent
  *
  * It represents a common event that is generated by the various components on the codal device.
  */
#include "DeviceConfig.h"
#include "DeviceEvent.h"
#include "Timer.h"
#include "EventModel.h"

using namespace codal;

EventModel* EventModel::defaultEventBus = NULL;

/**
  * Constructor.
  *
  * @param src The id of the Device Component that generated the event e.g. DEVICE_ID_BUTTON_A.
  *
  * @param value A component specific code indicating the cause of the event.
  *
  * @param mode Optional definition of how the event should be processed after construction (if at all):
  *                 CREATE_ONLY: DeviceEvent is initialised, and no further processing takes place.
  *                 CREATE_AND_FIRE: DeviceEvent is initialised, and its event handlers are immediately fired (not suitable for use in interrupts!).
  *
  * @code
  * // Create and launch an event using the default configuration
  * DeviceEvent evt(id,DEVICE_BUTTON_EVT_CLICK);
  *
  * // Create an event only, do not fire onto an EventModel.
  * DeviceEvent evt(id,DEVICE_BUTTON_EVT_CLICK,CREATE_AND_FIRE);
  * @endcode
  */
DeviceEvent::DeviceEvent(uint16_t source, uint16_t value, DeviceEventLaunchMode mode)
{
    this->source = source;
    this->value = value;
    this->timestamp = system_timer_current_time_us();

    if(mode != CREATE_ONLY)
        this->fire();
}

/**
  * Default constructor - initialises all values, and sets timestamp to the current time.
  */
DeviceEvent::DeviceEvent()
{
    this->source = 0;
    this->value = 0;
    this->timestamp = system_timer_current_time_us();
}

/**
  * Fires this DeviceEvent onto the Default EventModel, or a custom one!
  */
void DeviceEvent::fire()
{
    if(EventModel::defaultEventBus)
        EventModel::defaultEventBus->send(*this);
}


/**
  * Constructor.
  * Create a new DeviceEventQueueItem.
  *
  * @param evt The event to be queued.
  */
DeviceEventQueueItem::DeviceEventQueueItem(DeviceEvent evt)
{
    this->evt = evt;
    this->next = NULL;
}
